### ISSUE TITLE
Suggestion: make autocomplete also work with code from included files

### ISSUE THREAD

**Issue by SpacEagle17** [GeForceLegend/vscode-glsl#3]
When using https://github.com/stef-levesque/vscode-shader if you start typing words get recommended that come from included files, this is especially useful when having a global config file for all defines that you include everywhere. 
![image](https://user-images.githubusercontent.com/46494907/206903759-cda47c34-e26a-419b-9c0c-d6d49b56c323.png)
This is the only thing I'm missing from this extension and this is how it currently looks:
![image](https://user-images.githubusercontent.com/46494907/206903845-c6731e98-685d-4bd3-bf5f-a6f573185cfc.png)

**Comment by GeForceLegend** [comment]
That is not auto complete provided by vscode-shaders, but by vscode itself. For special color for defination, this extension uses a special textmate token for macros in ``#define``, that may cause vscode doesnt consider it as a common variable so part of auto completes are not available. Maybe I'll find some way to highlight it better in the future.

Besides that, if you are writing a shader pack for Minecraft Java Edition, https://github.com/Strum355/mcshader-lsp is a good extension though it depends on vscode-shaders. If you want to use both of this extension and my syntax highlighting, you can try replace the syntax providing files to vscode-shaders, or ask strum to let him delete dependencies.

**Comment by GeForceLegend** [comment]
v0.2.7 partly fixed this

**Comment by SpacEagle17** [comment]
Thanks, that did indeed fixed it for me!
