### ISSUE TITLE
`gl_Back(Vertex|Instance)` should be `gl_Base(Vertex|Index)`

### ISSUE THREAD

**Issue by SentientCoffee** [GeForceLegend/vscode-glsl#4]
On [line 409](https://github.com/GeForceLegend/vscode-glsl/blob/e6e328489a42ddbf04981c2a6b56c937d24ec828/syntaxes/glsl.tmLanguage.json#L409) of the `glsl.tmLanguage.json` file, there seems to be a typo for `\\bgl_Back(Vertex|Instance)|...`, which should be `\\bgl_Base(Vertex|Instance)|...`. If this is intended then the `gl_Base*` variables should be added to the regex.

**Comment by GeForceLegend** [comment]
Thanks for this catch
